/**
 * Extra search terms per FAQ section.
 *
 * The FAQ is the source of truth for answers; these are only vocabularies for
 * finding a section, drawn from how people describe the problem (and from the
 * wording already used inside the section). Keep a slug in sync with the heading
 * it belongs to — `test/faq.test.ts` fails if one goes stale.
 */
export const SECTION_ALIASES: Record<string, string[]> = {
  'getting-help--who-to-contact': [
    'contact',
    'support',
    'who do i message',
    'dm staff',
    'staff',
    'moderator',
    'discord',
    'help ticket',
    'email support',
    'ticket',
  ],
  'network-issues': [
    'cant connect',
    'cannot connect',
    'connection',
    'connect',
    'offline',
    'no internet',
    'internet',
    'network',
    'timeout',
    'timeouts',
    'dns',
    'vpn',
    'proxy',
    'firewall',
    'antivirus',
    'warp',
    'portmaster',
    'static ip',
    'dynamic ip',
    'blocked',
    'cannot reach server',
    'reconnecting',
  ],
  'freebucks-currency--daily-limits': [
    'freebucks',
    'currency',
    'credits',
    'usage credits',
    'daily limit',
    'limit reached',
    'out of credits',
    'wallet',
    'region',
    'plan bonus',
    'streak',
    'quota',
    'usage',
    'ran out of usage',
    'refill',
  ],
  'freebucks-refunds': [
    'refund',
    'refunds',
    'money back',
    'cancel subscription',
    'billing',
    'charged',
    'payment',
    'paid',
    'subscription',
    'annual plan',
  ],
  'agent-system--best-practices': [
    'agent',
    'agents',
    'custom agent',
    'vows',
    'best practices',
    'stuck in a loop',
    'thinking loop',
    'reasoning level',
  ],
  'using-freebuff-cloud': [
    'cloud',
    'github app',
    'connect repo',
    'deploy',
    'domain',
    'preview',
    'custom domain',
    'publish site',
  ],
  'mission-mode': ['mission', 'mission mode', 'goal', 'judge model', 'preset'],
  'bans--false-positives': [
    'banned',
    'ban',
    'false positive',
    'false positive ban',
    'account disabled',
    'suspended',
    'appeal',
  ],
  'mcp-server-setup-beta': [
    'mcp',
    'connectors',
    'custom server',
    'mcp config',
    'not ready',
    'connector',
  ],
  'installation-paths': [
    'install path',
    'install location',
    'installed',
    'install dir',
    'where is it installed',
    'appdata',
    'program files',
  ],
  'cloud-archiving-issues': [
    'archiving',
    'stuck archiving',
    'daytona',
    'delete project',
    'stuck',
  ],
  'opening-a-project-desktop': [
    'open project',
    'cant find project',
    'open button',
    'recent projects',
    'missing project',
  ],
  'about-requesting-models': [
    'add model',
    'request model',
    'model list',
    'cache hit pricing',
    'new models',
  ],
  'getting-your-project-url': [
    'project url',
    'share link',
    'link to project',
    'share project',
  ],
  'exporting-code--migrating-your-database': [
    'export',
    'export code',
    'download code',
    'migrate',
    'convex',
    'self host',
    'self-hosted',
    'backup',
    'database',
    'leave freebuff',
  ],
  'crash-on-start--updating': [
    'crash',
    'crashes',
    'crashing',
    'crash on start',
    'wont start',
    'will not start',
    'wont open',
    'wont launch',
    'fails to launch',
    'freeze',
    'frozen',
    'hangs',
    'not opening',
    'black screen',
    'white screen',
    'stuck on loading',
    'update',
    'updating',
    'update loop',
    'auto update',
    'update stuck',
    'reinstall',
    'older pc',
  ],
  'freebuff-mobile': [
    'mobile',
    'phone',
    'ios',
    'android',
    'remote control',
    'tailscale',
    'app store',
  ],
  'session--context-recovery': [
    'session',
    'session lost',
    'lost context',
    'lost conversation',
    'lost work',
    'chat history',
    'chats',
    'recover',
    'recovery',
    'logs',
    'log files',
    'crash log',
    'orchestrator stderr',
    'interrupted prompt',
    'resume',
    'history',
  ],
  'repository-submission-program': [
    'submit repo',
    'repository submission',
    'reward',
    'resubmit',
    'repository program',
    'bounty',
  ],
  'known-bugs--status-notes': [
    'known bug',
    'known issues',
    'status',
    'request body over 16777216 bytes',
    'needs a refill',
    'outage',
    'service status',
  ],
  'quick-start': [
    'get started',
    'getting started',
    'install cli',
    'setup',
    'first run',
    'how do i start',
    'tutorial',
  ],
  'official-faq-highlights': [
    'what is it for',
    'which models',
    'claude subscription',
    'open source',
    'docker',
    'sandbox',
    'ignore files',
    'codebuffignore',
    'support email',
  ],
  modes: [
    'mode',
    'modes',
    'max mode',
    'lite mode',
    'plan mode',
    'default mode',
    'shift tab',
    'switch mode',
  ],
  'knowledge-files': [
    'knowledge',
    'knowledge.md',
    'agents.md',
    'claude.md',
    'init',
    'instructions',
    'context file',
    'conventions',
  ],
  'mcp-servers': [
    'mcp',
    'mcp.json',
    'mcp servers',
    'notion',
    'stdio',
    'sse',
    'custom tool',
  ],
  skills: [
    'skill',
    'skills',
    'skill.md',
    'slash command',
    'skill not showing up',
  ],
  'what-makes-it-different-per-the-vendor': [
    'faster than claude code',
    'benchmark',
    'why freebuff',
    'advantages',
    'ads',
    'ad revenue',
  ],
  'how-it-actually-works': [
    'how it works',
    'subagents',
    'file picker',
    'orchestrator',
    'buffy',
    'pipeline',
    'reviewer',
  ],
  'working-with-large-codebases': [
    'large codebase',
    'big repo',
    'monorepo',
    'context too big',
    'slow on big repo',
    'cwd flag',
  ],
  'troubleshooting-official': [
    'troubleshooting',
    'command not found',
    'not recognized',
    'permission denied',
    'eacces',
    'enotempty',
    'chown',
    'takeown',
    'path',
    'global install',
    'version',
    'cached binary',
    'homebrew',
    'nvm',
    'fnm',
    'which node',
    'conflicting node',
    'tmux',
    'weirdness',
    'reinstall node',
  ],
  'sdk--programmatic-access': [
    'sdk',
    'api key',
    'codebuffclient',
    'automation',
    'programmatic',
    'ci cd',
    'github actions',
  ],
  privacy: ['privacy', 'data', 'training', 'ads', 'gdpr', 'personal data'],
}
